#!/usr/bin/env bash
# Installs and configures Nginx to display "Holberton School for the win!"

# Update and install nginx
apt-get update -y
apt-get install nginx -y

# Create the HTML file in the default web root
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Restart nginx (no systemctl)
service nginx restart

