#!/usr/bin/env bash
# Installs and configures nginx to serve a page with "Holberton School"

# Update package info and install nginx
apt-get update -y
apt-get install -y nginx

# Make sure nginx is enabled and started
service nginx start

# Replace the default index page
echo "Holberton School" | tee /var/www/html/index.nginx-debian.html > /dev/null

# Ensure the default nginx config listens on port 80 and points to /var/www/html
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
}
" > /etc/nginx/sites-available/default

# Restart nginx to apply changes (without using systemctl)
service nginx restart

