#!/usr/bin/env bash
# Configure Nginx custom 404 page

# Install nginx
apt-get update -y
apt-get install -y nginx

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Update Nginx default config
sed -i 's|try_files \$uri \$uri/ =404;|try_files \$uri \$uri/ /404.html;|' /etc/nginx/sites-available/default

# Add error_page directive (if not already present)
if ! grep -q "error_page 404 /404.html;" /etc/nginx/sites-available/default; then
    sed -i '/server_name _;/a \    error_page 404 /404.html;' /etc/nginx/sites-available/default
fi

# Restart nginx
service nginx restart

